name: Build Android APK with Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Используем официальный Docker-образ от разработчиков Kivy
    container:
      image: kivy/buildozer:master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Git Safe Directory
      run: |
        git config --global --add safe.directory /__w/geotelo-gis/geotelo-gis

    - name: Clean previous failed builds
      run: |
        # Полная очистка временных файлов сборки для исключения старых конфликтов
        buildozer android clean

    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Geotelo-GIS-Android-APK
        path: bin/*.apk
        if-no-files-found: error
