name: Build Android APK with Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Essential System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libsqlite3-dev \
          bzip2 \
          libbz2-dev \
          libssl-dev \
          libffi-dev \
          ccache

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        pip install git+https://github.com/kivy/buildozer.git@master

    - name: Build APK with Buildozer
      run: |
        # 1. Запускаем предварительную инициализацию Android SDK, чтобы создались папки
        buildozer android list || true
        
        # 2. Принудительно подписываем ВСЕ лицензии Android SDK штатными средствами Google
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "\n2c40c06d1d38eae19811b98511d09a31010e958f\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910\n89ac3033e0a62c11b6d206d7463ea2748a3ea30e\nb7a869d6f77cce83c14da57a462e07907532a22a\n843dc6c5b85f740f10f2d65482e1680d342167b3" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        
        # 3. Запуск основной чистой сборки
        buildozer -v android debug
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Geotelo-GIS-Android-APK
        path: bin/*.apk
        if-no-files-found: error
