name: Build Android APK with Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev gawk unzip git ccache zip libffi-dev libssl-dev
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: build apk
      run: |
        # Автоматически принимаем все лицензии Android SDK перед сборкой
        yes | buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Geotelo-Android-APK
        path: bin/*.apk
